# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dependencies.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import dependency1_pb2 as dependency1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x65pendencies.proto\x12\x0c\x64\x65pendencies\x1a\x11\x64\x65pendency1.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xbb\x02\n\x07Greeter\x12\x42\n\x08SayHello\x12\x1a.dependencies.HelloRequest\x1a\x18.dependencies.HelloReply\"\x00\x12O\n\x13SayHelloStreamReply\x12\x1a.dependencies.HelloRequest\x1a\x18.dependencies.HelloReply\"\x00\x30\x01\x12P\n\x12SayHelloBidiStream\x12\x1a.dependencies.HelloRequest\x1a\x18.dependencies.HelloReply\"\x00(\x01\x30\x01\x12I\n\x0fHasDependencies\x12\x19.dependencies.Dependency1\x1a\x19.dependencies.Dependency1\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dependencies_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HELLOREQUEST']._serialized_start=55
  _globals['_HELLOREQUEST']._serialized_end=83
  _globals['_HELLOREPLY']._serialized_start=85
  _globals['_HELLOREPLY']._serialized_end=114
  _globals['_GREETER']._serialized_start=117
  _globals['_GREETER']._serialized_end=432
# @@protoc_insertion_point(module_scope)
