#!/bin/bash

# Run this script before commits to review complexity reports generated by
# wily.

wily build ./src/grpc_requests/
wily report ./src/grpc_requests/client.py -n 2 complexity mi difficulty
wily report ./src/grpc_requests/aio.py -n 2 complexity mi difficulty
wily report ./src/grpc_requests/utils.py -n 2 complexity mi difficulty