# Continue supporting python 3.7
target-version = "py37"

[lint]
# Bugbear Rules
select = ["E4", "E7", "E9", "C4", "C90", "F", "B", "SIM", "PERF"]

# Do not enforce line length issues
ignore = ["E501"]

# Don't fix bugbears
unfixable = ["B"]

[lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]



